### ISSUE TITLE
[iCloud] Selecting a photo from an album that has the pictures in iCloud and cannot be downloaded crashes the app.

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [DragonCherry/AssetsPickerViewController#27]
The current state assumes the selected thumbnails also exist in the User's phone, but sometimes they need to be downloaded from iCloud. If the downloading fails, which happens quite a lot, then no image is being stored. Some kind of safe logic preventing this to happen would be cool!

Thanks for the hard work!

**Comment by mikemike396** [comment]
We are running into some issues where the below method returns null. I am curious about this issue you opened. How did you reproduce iCloud photos not being downloaded?

```
- (void)assetsPickerWithController:(AssetsPickerViewController *)controller selected:(NSArray<PHAsset *> *)assets
{
    for (PHAsset *asset in assets)
    {
        [asset getURLWithCompletion:^(NSURL *URL) {}
    }
}
```

**Comment by JoseSanchezMirandaRos** [comment]
Hi Mike,

The problem I think is when iCloud itself fails. I use iCloud for my personal use and sometimes when you tap on a photo you wanna see, the photo has to be downloaded from iCloud to display the full version...well, that download fails very often actually and apple shows an alert, when that happens I am guessing the PHAsset comes back nil and that's what was causing the issue for me. I used it on my app, crashed, went to my photo library and iCloud was giving me errors non stop. The way I dealt with it is to set up a timer and display an activity indicator, after the timer is out, if the response is still nil, then I show an error letting the the know that asset couldn't be downloaded from iCloud. Something like that. oh! and I had full wifi or LTE every time I tried to download from iCloud. So, when you encounter the issue, go to your photos app and try to downloaded from iCloud there, you'll see it also fails!

**Comment by mikemike396** [comment]
Interesting, thank you for the feedback and suggested fix.

**Comment by JoseSanchezMirandaRos** [comment]
Thanks for the hard work! I love this pod!

**Comment by moin-hassan** [comment]
Hi, has this been fixed in recent commits? I used this library some time ago and encountered the same issue as well.
Thanks

**Comment by mikemike396** [comment]
Any update on this?? iCloud downloads still fail for us sometimes and return null objects.

**Comment by mikemike396** [comment]
Awesome! Let me know if you need any help. I can test and such. This will be a huge help to our application.

Thanks

**Comment by JoseSanchezMirandaRos** [comment]
hey @mikemike396, I was digging into y code and I fixed on the app level, not the actual library since it doesn't support iCloud downloads at all.

This is what I did, created a method that gets an UIImage:

`func getUIImage(asset: PHAsset) -> UIImage? {
    var img: UIImage?
    let manager = PHImageManager.default()
    let options = PHImageRequestOptions()
    options.version = .original
    options.deliveryMode = .highQualityFormat
    options.isSynchronous = true
    options.isNetworkAccessAllowed = true
    manager.requestImageData(for: asset, options: options) { data, _, _, _ in
        
        if let data = data {
            img = UIImage(data: data)
        }
    }
    return img
}`

Then created another method to show the download error alert:

`func showDownloadErrorAlert() {
    let alert = UIAlertController(title: "Your iCloud error title", message: "Your error message", preferredStyle: .alert)
    let okAction = UIAlertAction(title: "OK", style: .default, handler: { action in
        self.dismiss(animated: true, completion: nil)
    })
    alert.addAction(okAction)
    present(alert,animated: true,completion: nil)
}`

and finally called the library method where I basically show the error if the asset, in this case of type image, comes back as nil:

`func assetsPicker(controller: AssetsPickerViewController, selected assets: [PHAsset]) {
    for asset in assets {
        if asset.mediaType == PHAssetMediaType.image {
            // get image from PHAsset
            self.extraImage = self.getUIImage(asset: asset)
            guard self.extraImage != nil else {
                // show alert image could not be downloaded
                DispatchQueue.main.async {
                    self.showDownloadErrorAlert()
                }
                return
            }
        }
    }
}`


Let me know if that helps you!

**Comment by mikemike396** [comment]
@JoseSanchezMirandaRos Thank you so much for sharing your code. So this is more of a guard against the null reference if the image is not downloaded via iCloud? Doesn't actually handle the iCloud download issue?

**Comment by ramohanreddy** [comment]
Hi  @mikemike396 and @JoseSanchezMirandaRos 
I am fetching multiple video assets from PHAssets.But  i need AVAssetsurl form PHAssets ,some time i am getting nil . Pls tell me any solution for this.
I am using below code

 ```
self.getURL(ofPhotoWith: self.assets[i], completionHandler: { Result in
                                            print("NEW_VIDEO_AVURL\(Result)")
               
            })
```


 ```
  func getURL(ofPhotoWith mPhasset: PHAsset, completionHandler : @escaping ((_ responseURL : URL?) -> Void)) {
        
        if mPhasset.mediaType == .image {
            let options: PHContentEditingInputRequestOptions = PHContentEditingInputRequestOptions()
            options.canHandleAdjustmentData = {(adjustmeta: PHAdjustmentData) -> Bool in
                return true
            }
            mPhasset.requestContentEditingInput(with: options, completionHandler: { (contentEditingInput, info) in
                completionHandler(contentEditingInput!.fullSizeImageURL)
            })
        } else if mPhasset.mediaType == .video {
            let options = PHVideoRequestOptions()
            options.version = .original
            options.deliveryMode = .highQualityFormat
            options.isNetworkAccessAllowed = true

            
            PHImageManager.default().requestAVAsset(forVideo: mPhasset, options: options, resultHandler: { (asset, audioMix, info) in
                if let urlAsset = asset as? AVURLAsset {
                    let localVideoUrl = urlAsset.url
                    completionHandler(localVideoUrl)
                } else {
                    completionHandler(nil)
                }
            })
        }
        
    }
```

Thanks&Regards
Ramohan Reddy

**Comment by mikemike396** [comment]
> Hi @mikemike396 and @JoseSanchezMirandaRos
> I am fetching multiple video assets from PHAssets.But i need AVAssetsurl form PHAssets ,some time i am getting nil . Pls tell me any solution for this.
> I am using below code
> 
> ```
> self.getURL(ofPhotoWith: self.assets[i], completionHandler: { Result in
>                                            print("NEW_VIDEO_AVURL\(Result)")
>               
>            })
> ```
> ```
>  func getURL(ofPhotoWith mPhasset: PHAsset, completionHandler : @escaping ((_ responseURL : URL?) -> Void)) {
>        
>        if mPhasset.mediaType == .image {
>            let options: PHContentEditingInputRequestOptions = PHContentEditingInputRequestOptions()
>            options.canHandleAdjustmentData = {(adjustmeta: PHAdjustmentData) -> Bool in
>                return true
>            }
>            mPhasset.requestContentEditingInput(with: options, completionHandler: { (contentEditingInput, info) in
>                completionHandler(contentEditingInput!.fullSizeImageURL)
>            })
>        } else if mPhasset.mediaType == .video {
>            let options = PHVideoRequestOptions()
>            options.version = .original
>            options.deliveryMode = .highQualityFormat
>            options.isNetworkAccessAllowed = true
> 
>            
>            PHImageManager.default().requestAVAsset(forVideo: mPhasset, options: options, resultHandler: { (asset, audioMix, info) in
>                if let urlAsset = asset as? AVURLAsset {
>                    let localVideoUrl = urlAsset.url
>                    completionHandler(localVideoUrl)
>                } else {
>                    completionHandler(nil)
>                }
>            })
>        }
>        
>    }
> ```
> Thanks&Regards
> Ramohan Reddy

When the fetch the images are they coming from iCloud? If so please follow this post and basically look for a null case and show an alert that it couldn't be downloaded. This is not the best solution, but at this time the library does not support iCloud download.
